tileset = {
	name = "zelda",
	number_of_tiles = 10,
	texture = "tileset.png",
	tile_0 = { type = 0, source_frame_position = { x = 0, y = 0, }, },
	tile_1 = { type = 0, source_frame_position = { x = 1, y = 0, }, },
	tile_2 = { type = 0, source_frame_position = { x = 2, y = 0, }, },
	tile_3 = { type = 0, source_frame_position = { x = 3, y = 0, }, },
	tile_4 = { type = 0, source_frame_position = { x = 4, y = 0, }, },
	tile_5 = { type = 0, source_frame_position = { x = 5, y = 0, }, },
	tile_6 = { type = 0, source_frame_position = { x = 6, y = 0, }, },
	tile_7 = { type = 0, source_frame_position = { x = 7, y = 0, }, },
	tile_8 = { type = 0, source_frame_position = { x = 8, y = 0, }, },
	tile_9 = { type = 0, source_frame_position = { x = 9, y = 0, }, },
}