tileset = {
	-- Tileset Config
	name = "default",
	number_of_tiles = 100,
	texture = "tileset.png",
	-- Tile Row 0
	tile_0 = { type = 0, source_frame_position = { x = 0, y = 0, }, },
	tile_1 = { type = 0, source_frame_position = { x = 1, y = 0, }, },
	tile_2 = { type = 0, source_frame_position = { x = 2, y = 0, }, },
	tile_3 = { type = 0, source_frame_position = { x = 3, y = 0, }, },
	tile_4 = { type = 0, source_frame_position = { x = 4, y = 0, }, },
	tile_5 = { type = 0, source_frame_position = { x = 5, y = 0, }, },
	tile_6 = { type = 0, source_frame_position = { x = 6, y = 0, }, },
	tile_7 = { type = 0, source_frame_position = { x = 7, y = 0, }, },
	tile_8 = { type = 0, source_frame_position = { x = 8, y = 0, }, },
	tile_9 = { type = 0, source_frame_position = { x = 9, y = 0, }, },
	-- Tile Row 1
	tile_10 = { type = 0, source_frame_position = { x = 0, y = 1, }, },
	tile_11 = { type = 1, source_frame_position = { x = 1, y = 1, }, },
	tile_12 = { type = 1, source_frame_position = { x = 2, y = 1, }, },
	tile_13 = { type = 1, source_frame_position = { x = 3, y = 1, }, },
	tile_14 = { type = 1, source_frame_position = { x = 4, y = 1, }, },
	tile_15 = { type = 1, source_frame_position = { x = 5, y = 1, }, },
	tile_16 = { type = 1, source_frame_position = { x = 6, y = 1, }, },
	tile_17 = { type = 1, source_frame_position = { x = 7, y = 1, }, },
	tile_18 = { type = 1, source_frame_position = { x = 8, y = 1, }, },
	tile_19 = { type = 0, source_frame_position = { x = 9, y = 1, }, },
	-- Tile Row 2
	tile_20 = { type = 1, source_frame_position = { x = 0, y = 2, }, },
	tile_21 = { type = 1, source_frame_position = { x = 1, y = 2, }, },
	tile_22 = { type = 1, source_frame_position = { x = 2, y = 2, }, },
	tile_23 = { type = 0, source_frame_position = { x = 3, y = 2, }, },
	tile_24 = { type = 1, source_frame_position = { x = 4, y = 2, }, },
	tile_25 = { type = 1, source_frame_position = { x = 5, y = 2, }, },
	tile_26 = { type = 1, source_frame_position = { x = 6, y = 2, }, },
	tile_27 = { type = 1, source_frame_position = { x = 7, y = 2, }, },
	tile_28 = { type = 1, source_frame_position = { x = 8, y = 2, }, },
	tile_29 = { type = 1, source_frame_position = { x = 9, y = 2, }, },
	-- Tile Row 3
	tile_30 = { type = 1, source_frame_position = { x = 0, y = 3, }, },
	tile_31 = { type = 1, source_frame_position = { x = 1, y = 3, }, },
	tile_32 = { type = 1, source_frame_position = { x = 2, y = 3, }, },
	tile_33 = { type = 1, source_frame_position = { x = 3, y = 3, }, },
	tile_34 = { type = 1, source_frame_position = { x = 4, y = 3, }, },
	tile_35 = { type = 1, source_frame_position = { x = 5, y = 3, }, },
	tile_36 = { type = 1, source_frame_position = { x = 6, y = 3, }, },
	tile_37 = { type = 1, source_frame_position = { x = 7, y = 3, }, },
	tile_38 = { type = 1, source_frame_position = { x = 8, y = 3, }, },
	tile_39 = { type = 1, source_frame_position = { x = 9, y = 3, }, },
	-- Tile Row 4
	tile_40 = { type = 1, source_frame_position = { x = 0, y = 4, }, },
	tile_41 = { type = 1, source_frame_position = { x = 1, y = 4, }, },
	tile_42 = { type = 1, source_frame_position = { x = 2, y = 4, }, },
	tile_43 = { type = 1, source_frame_position = { x = 3, y = 4, }, },
	tile_44 = { type = 1, source_frame_position = { x = 4, y = 4, }, },
	tile_45 = { type = 1, source_frame_position = { x = 5, y = 4, }, },
	tile_46 = { type = 1, source_frame_position = { x = 6, y = 4, }, },
	tile_47 = { type = 1, source_frame_position = { x = 7, y = 4, }, },
	tile_48 = { type = 1, source_frame_position = { x = 8, y = 4, }, },
	tile_49 = { type = 1, source_frame_position = { x = 9, y = 4, }, },
	-- Tile Row 5
	tile_50 = { type = 1, source_frame_position = { x = 0, y = 5, }, },
	tile_51 = { type = 1, source_frame_position = { x = 1, y = 5, }, },
	tile_52 = { type = 1, source_frame_position = { x = 2, y = 5, }, },
	tile_53 = { type = 1, source_frame_position = { x = 3, y = 5, }, },
	tile_54 = { type = 1, source_frame_position = { x = 4, y = 5, }, },
	tile_55 = { type = 1, source_frame_position = { x = 5, y = 5, }, },
	tile_56 = { type = 1, source_frame_position = { x = 6, y = 5, }, },
	tile_57 = { type = 1, source_frame_position = { x = 7, y = 5, }, },
	tile_58 = { type = 1, source_frame_position = { x = 8, y = 5, }, },
	tile_59 = { type = 1, source_frame_position = { x = 9, y = 5, }, },
	-- Tile Row 6
	tile_60 = { type = 1, source_frame_position = { x = 0, y = 6, }, },
	tile_61 = { type = 1, source_frame_position = { x = 1, y = 6, }, },
	tile_62 = { type = 1, source_frame_position = { x = 2, y = 6, }, },
	tile_63 = { type = 1, source_frame_position = { x = 3, y = 6, }, },
	tile_64 = { type = 1, source_frame_position = { x = 4, y = 6, }, },
	tile_65 = { type = 1, source_frame_position = { x = 5, y = 6, }, },
	tile_66 = { type = 1, source_frame_position = { x = 6, y = 6, }, },
	tile_67 = { type = 1, source_frame_position = { x = 7, y = 6, }, },
	tile_68 = { type = 1, source_frame_position = { x = 8, y = 6, }, },
	tile_69 = { type = 1, source_frame_position = { x = 9, y = 6, }, },
	-- Tile Row 7
	tile_70 = { type = 1, source_frame_position = { x = 0, y = 7, }, },
	tile_71 = { type = 1, source_frame_position = { x = 1, y = 7, }, },
	tile_72 = { type = 1, source_frame_position = { x = 2, y = 7, }, },
	tile_73 = { type = 1, source_frame_position = { x = 3, y = 7, }, },
	tile_74 = { type = 1, source_frame_position = { x = 4, y = 7, }, },
	tile_75 = { type = 1, source_frame_position = { x = 5, y = 7, }, },
	tile_76 = { type = 1, source_frame_position = { x = 6, y = 7, }, },
	tile_77 = { type = 1, source_frame_position = { x = 7, y = 7, }, },
	tile_78 = { type = 1, source_frame_position = { x = 8, y = 7, }, },
	tile_79 = { type = 1, source_frame_position = { x = 9, y = 7, }, },
	-- Tile Row 8
	tile_80 = { type = 1, source_frame_position = { x = 0, y = 8, }, },
	tile_81 = { type = 1, source_frame_position = { x = 1, y = 8, }, },
	tile_82 = { type = 1, source_frame_position = { x = 2, y = 8, }, },
	tile_83 = { type = 1, source_frame_position = { x = 3, y = 8, }, },
	tile_84 = { type = 1, source_frame_position = { x = 4, y = 8, }, },
	tile_85 = { type = 1, source_frame_position = { x = 5, y = 8, }, },
	tile_86 = { type = 1, source_frame_position = { x = 6, y = 8, }, },
	tile_87 = { type = 1, source_frame_position = { x = 7, y = 8, }, },
	tile_88 = { type = 1, source_frame_position = { x = 8, y = 8, }, },
	tile_89 = { type = 1, source_frame_position = { x = 9, y = 8, }, },
	-- Tile Row 9
	tile_90 = { type = 1, source_frame_position = { x = 0, y = 9, }, },
	tile_91 = { type = 1, source_frame_position = { x = 1, y = 9, }, },
	tile_92 = { type = 1, source_frame_position = { x = 2, y = 9, }, },
	tile_93 = { type = 1, source_frame_position = { x = 3, y = 9, }, },
	tile_94 = { type = 1, source_frame_position = { x = 4, y = 9, }, },
	tile_95 = { type = 1, source_frame_position = { x = 5, y = 9, }, },
	tile_96 = { type = 1, source_frame_position = { x = 6, y = 9, }, },
	tile_97 = { type = 1, source_frame_position = { x = 7, y = 9, }, },
	tile_98 = { type = 1, source_frame_position = { x = 8, y = 9, }, },
	tile_99 = { type = 1, source_frame_position = { x = 9, y = 9, }, },
}
