#ifndef ARKENGINE_ENGINECONFIG_H_
#define ARKENGINE_ENGINECONFIG_H_

// Useful constants to the Engine.
const float PI = 3.14159265358979323f;
const int TILE_SIZE_X = 16;
const int TILE_SIZE_Y = 16;
const int WINDOW_TILE_GRID_X = 16;
const int WINDOW_TILE_GRID_Y = 14;
const int MINIMUM_WINDOW_SIZE_WIDTH = TILE_SIZE_X * WINDOW_TILE_GRID_X;
const int MINIMUM_WINDOW_SIZE_HEIGHT = TILE_SIZE_Y * WINDOW_TILE_GRID_Y;

#endif